# CMake generated Testfile for 
# Source directory: E:/Ducuments/codeForVScode/MatCal
# Build directory: E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("matcal_characterization_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_characterization_tests.exe")
set_tests_properties("matcal_characterization_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;212;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;215;matcal_add_legacy_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_legacy_triangular_regression_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_legacy_triangular_regression_tests.exe")
set_tests_properties("matcal_legacy_triangular_regression_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;212;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;219;matcal_add_legacy_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_legacy_zero_size_regression_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_legacy_zero_size_regression_tests.exe")
set_tests_properties("matcal_legacy_zero_size_regression_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;212;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;223;matcal_add_legacy_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_legacy_numerics_regression_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_legacy_numerics_regression_tests.exe")
set_tests_properties("matcal_legacy_numerics_regression_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;212;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;227;matcal_add_legacy_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_legacy_sor_regression_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_legacy_sor_regression_tests.exe")
set_tests_properties("matcal_legacy_sor_regression_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;212;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;231;matcal_add_legacy_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_legacy_matrix_linalg_adapter_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_legacy_matrix_linalg_adapter_tests.exe")
set_tests_properties("matcal_legacy_matrix_linalg_adapter_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;212;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;235;matcal_add_legacy_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_polynomial_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_polynomial_tests.exe")
set_tests_properties("matcal_polynomial_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;250;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;295;matcal_add_polynomial_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_polynomial_public_header_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_polynomial_public_header_tests.exe")
set_tests_properties("matcal_polynomial_public_header_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;250;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;299;matcal_add_polynomial_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_polynomial_multi_tu_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_polynomial_multi_tu_tests.exe")
set_tests_properties("matcal_polynomial_multi_tu_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;250;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;304;matcal_add_polynomial_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_roots_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_roots_tests.exe")
set_tests_properties("matcal_roots_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;257;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;310;matcal_add_roots_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_interpolation_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_interpolation_tests.exe")
set_tests_properties("matcal_interpolation_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;264;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;314;matcal_add_interpolation_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_interpolation_remaining_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_interpolation_remaining_tests.exe")
set_tests_properties("matcal_interpolation_remaining_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;264;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;318;matcal_add_interpolation_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_roots_interpolation_public_header_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_roots_interpolation_public_header_tests.exe")
set_tests_properties("matcal_roots_interpolation_public_header_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;334;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_roots_interpolation_multi_tu_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_roots_interpolation_multi_tu_tests.exe")
set_tests_properties("matcal_roots_interpolation_multi_tu_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;347;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_pt_style_consumer_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_pt_style_consumer_tests.exe")
set_tests_properties("matcal_pt_style_consumer_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;354;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_calculus_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_calculus_tests.exe")
set_tests_properties("matcal_calculus_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;271;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;356;matcal_add_calculus_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_ode_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_ode_tests.exe")
set_tests_properties("matcal_ode_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;278;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;360;matcal_add_ode_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_calculus_ode_public_header_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_calculus_ode_public_header_tests.exe")
set_tests_properties("matcal_calculus_ode_public_header_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;374;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_calculus_ode_multi_tu_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_calculus_ode_multi_tu_tests.exe")
set_tests_properties("matcal_calculus_ode_multi_tu_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;386;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_calculus_only_consumer_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_calculus_only_consumer_tests.exe")
set_tests_properties("matcal_calculus_only_consumer_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;393;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_ode_only_consumer_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_ode_only_consumer_tests.exe")
set_tests_properties("matcal_ode_only_consumer_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;400;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_nonlinear_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_nonlinear_tests.exe")
set_tests_properties("matcal_nonlinear_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;285;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;402;matcal_add_nonlinear_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_least_squares_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_least_squares_tests.exe")
set_tests_properties("matcal_least_squares_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;292;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;406;matcal_add_least_squares_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_nonlinear_least_squares_interpolation_public_header_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_nonlinear_least_squares_interpolation_public_header_tests.exe")
set_tests_properties("matcal_nonlinear_least_squares_interpolation_public_header_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;422;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_nonlinear_least_squares_interpolation_multi_tu_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_nonlinear_least_squares_interpolation_multi_tu_tests.exe")
set_tests_properties("matcal_nonlinear_least_squares_interpolation_multi_tu_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;437;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_nonlinear_only_consumer_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_nonlinear_only_consumer_tests.exe")
set_tests_properties("matcal_nonlinear_only_consumer_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;445;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_least_squares_only_consumer_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_least_squares_only_consumer_tests.exe")
set_tests_properties("matcal_least_squares_only_consumer_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;452;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_interpolation_only_consumer_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_interpolation_only_consumer_tests.exe")
set_tests_properties("matcal_interpolation_only_consumer_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;459;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_vector_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_vector_tests.exe")
set_tests_properties("matcal_linalg_vector_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;461;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_dense_matrix_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_dense_matrix_tests.exe")
set_tests_properties("matcal_linalg_dense_matrix_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;465;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_solver_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_solver_tests.exe")
set_tests_properties("matcal_linalg_solver_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;469;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_scale_contract_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_scale_contract_tests.exe")
set_tests_properties("matcal_linalg_scale_contract_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;473;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_iterative_solver_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_iterative_solver_tests.exe")
set_tests_properties("matcal_linalg_iterative_solver_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;477;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_eigen_solver_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_eigen_solver_tests.exe")
set_tests_properties("matcal_linalg_eigen_solver_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;481;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_skyline_matrix_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_skyline_matrix_tests.exe")
set_tests_properties("matcal_linalg_skyline_matrix_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;485;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_skyline_ldlt_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_skyline_ldlt_tests.exe")
set_tests_properties("matcal_linalg_skyline_ldlt_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;489;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_skyline_performance_contract_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_skyline_performance_contract_tests.exe")
set_tests_properties("matcal_linalg_skyline_performance_contract_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;493;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_public_header_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_public_header_tests.exe")
set_tests_properties("matcal_linalg_public_header_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;497;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_linalg_multi_tu_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_linalg_multi_tu_tests.exe")
set_tests_properties("matcal_linalg_multi_tu_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;243;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;509;matcal_add_linalg_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
add_test("matcal_multi_tu_link_tests" "E:/Ducuments/codeForVScode/MatCal/build-relwithdebinfo/matcal_multi_tu_link_tests.exe")
set_tests_properties("matcal_multi_tu_link_tests" PROPERTIES  _BACKTRACE_TRIPLES "E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;524;add_test;E:/Ducuments/codeForVScode/MatCal/CMakeLists.txt;0;")
